### ISSUE TITLE
errors when trying to build locally

### ISSUE THREAD

**Issue by michielbdejong** [interledger/interledger-website#45]
```sh
 yarn install
yarn install v1.22.11
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.1: The platform "linux" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > bootstrap@5.0.0-beta1" has unmet peer dependency "@popperjs/core@^2.5.4".
[4/4] Building fresh packages...
$ gulp dev:install
[12:16:51] Requiring external module @babel/register
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Running @cloudcannon/suite 2.0.2
Running @cloudcannon/screenshot-util 1.1.13
[12:16:56] Using gulpfile ~/interledger-website/gulpfile.babel.js
[12:16:56] Starting 'dev:install'...
[12:16:56] $ bundle install --path ../vendor/bundle
[12:16:56] 'dev:install' errored after 20 ms
[12:16:56] Error: spawn bundle ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by michielbdejong** [comment]
Ah, there is a Gemfile in ./src, will try to install Ruby 2.6.2

**Comment by michielbdejong** [comment]
Fixed in #46

**Comment by michielbdejong** [comment]
I also had to edit src/Gemfile to downgrade  sassc to version 2.1.0 due to https://stackoverflow.com/a/64201011/680454
And then the build still hangs for several minutes, but eventually it succeeded.

**Comment by AlexLakatos** [comment]
Thanks for filing the issue!
